### PR TITLE
allow eff studies

### PR DESCRIPTION
**Pull request by mmozercern**
HI Jose,

I tried to set things up so that nothing changes if you run the code without additional parameter, but if a third command line parameter is added, the relevant efficiency information gets filled.
Can you check that the trees do indeed not change at all if you do that?

Matthias

### CODE REVIEW

**Comment by jruizvar** [comment]
Not OK when running over background MC
- cmsRun backgrounds/analysis-background.py TT mu

----- Begin Fatal Exception 08-Apr-2016 15:06:13 CEST-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing run: 1 lumi: 47372 event: 9474399
   [1] Running path 'analysis'
   [2] Calling event method for module EDBRTreeMaker/'treeDumper'
Exception Message:
TriggerResultsByName has a null pointer to TriggerResults.
This probably means TriggerResults was not found in the Event
because the product was dropped or never created. It could also
mean it was requested for a process that does not exist or was
misspelled
   Additional Info:
      [a] If you wish to continue processing events after a ProductNotFound exception,
add "SkipEvent = cms.untracked.vstring('ProductNotFound')" to the "options" PSet in the configuration.

----- End Fatal Exception -------------------------------------------------

**Comment by mmozercern** [comment]
Ok, I think I fixed the issues for the backgrounds
Do you also have a test-config for the data?

**Comment by jruizvar** [comment]
- cd EDBRTreeMaker/promptReco/Run2015CD
- cmsRun analysis-data.py el

**Comment by mmozercern** [comment]
Ok, it should also work with data now. I ran on ~100k events

**Comment by jruizvar** [comment]
+1

**Pull request merged**
